dpkg_deploy element: Fix for API break in BuildStream core
Fixes the following traceback with BuildStream versions from
commit aa79d317ed373bc563deb789d8d62d49a0766f50:

    [00:00:23][f68506e0][build:dpkg-deploy-test.bst          ] BUG     dpkg-build-test/dpkg-deploy-test/f68506e0-build.8340.log

        An unhandled exception occured:

        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 265, in child_action
            result = self.action(element)
          File "/usr/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
            element._assemble()
          File "/usr/lib/python3.6/site-packages/buildstream/element.py", line 1092, in _assemble
            self.stage(sandbox)
          File "/usr/lib/python3.6/site-packages/bst_external/elements/dpkg_deploy.py", line 191, in stage
            utils.link_files(src, dst, package_splits)
        TypeError: link_files() takes 2 positional arguments but 3 were given